In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('datasets/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.csv', delimiter=',')

In [5]:
column_mapping = {
    'Timestamp': 'timestamp',
    'How old are you?': 'age',
    'What industry do you work in?': 'industry',
    'Job title': 'job_title',
    'If your job title needs additional context, please clarify here:': 'job_title_context',
    "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": 'annual_salary',
    'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.': 'additional_compensation',
    'Please indicate the currency': 'currency',
    'If "Other," please indicate the currency here: ': 'other_currency',
    'If your income needs additional context, please provide it here:': 'income_context',
    'What country do you work in?': 'country',
    "If you're in the U.S., what state do you work in?": 'state',
    'What city do you work in?': 'city',
    'How many years of professional work experience do you have overall?': 'total_experience_years',
    'How many years of professional work experience do you have in your field?': 'field_experience_years',
    'What is your highest level of education completed?': 'education_level',
    'What is your gender?': 'gender',
    'What is your race? (Choose all that apply.)': 'race'
}

df.rename(columns=column_mapping, inplace=True)

In [6]:
df.sample(5)

,timestamp,age,industry,job_title,job_title_context,annual_salary,additional_compensation,currency,other_currency,income_context,country,state,city,total_experience_years,field_experience_years,education_level,gender,race
26357,5/27/2021 16:30:37,25-34,Computing or Tech,Senior Software Engineer,NaN,160000,15000.0,USD,NaN,NaN,United States,California,San Francisco,8 - 10 years,5-7 years,Master's degree,Man,White
11223,4/27/2021 23:48:28,25-34,Education (Primary/Secondary),"Teacher, Secondary",NaN,"58,000",6000.0,USD,NaN,NaN,United States,Connecticut,Denver,8 - 10 years,5-7 years,Master's degree,Non-binary,White
15458,4/28/2021 17:07:43,35-44,Computing or Tech,Data Practice Lead,NaN,"121,000",10000.0,AUD/NZD,NaN,NaN,New Zealand,NaN,Wellington,8 - 10 years,5-7 years,College degree,Man,White
26057,5/11/2021 13:52:36,25-34,Engineering or Manufacturing,Staff Structural Enginner,Bridge Engineer,78000,5000.0,USD,NaN,NaN,United States of America,Florida,Jacksonville,5-7 years,5-7 years,Master's degree,Woman,White
18162,4/28/2021 22:54:15,25-34,Nonprofits,Outreach Coordinator,"I'm also the projects director, comms person, ...","44,000",0.0,USD,NaN,"I don't get benefits, access to insurance, or ...",US,Oregon,Portland,8 - 10 years,8 - 10 years,PhD,Woman,White

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28223 entries, 0 to 28222
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   timestamp                28223 non-null  str
 1   age                      28223 non-null  str
 2   industry                 28137 non-null  str
 3   job_title                28218 non-null  str
 4   job_title_context        7293 non-null   str
 5   annual_salary            28223 non-null  str
 6   additional_compensation  20849 non-null  float64
 7   currency                 28223 non-null  str
 8   other_currency           224 non-null    str
 9   income_context           3053 non-null   str
 10  country                  28221 non-null  str
 11  state                    23147 non-null  str
 12  city                     28138 non-null  str
 13  total_experience_years   28223 non-null  str
 14  field_experience_years   28223 non-null  str
 15  education_level          27982 non-null  str
 16  gender                   28037 non-null  str
 17  race                     28026 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

In [8]:
df.nunique()

timestamp                  25441
age                            7
industry                    1225
job_title                  14433
job_title_context           7029
annual_salary               4332
additional_compensation      849
currency                      11
other_currency               130
income_context              2988
country                      390
state                        138
city                        4875
total_experience_years         8
field_experience_years         8
education_level                6
gender                         5
race                          52
dtype: int64

In [9]:
df['annual_salary'] = pd.to_numeric(df['annual_salary'], errors='coerce')

In [10]:
df['additional_compensation'] = pd.to_numeric(df['additional_compensation'], errors='coerce')

In [11]:
df.isnull().sum().sort_values(ascending=False)

other_currency             27999
income_context             25170
job_title_context          20930
annual_salary              20302
additional_compensation     7374
state                       5076
education_level              241
race                         197
gender                       186
industry                      86
city                          85
job_title                      5
country                        2
timestamp                      0
age                            0
currency                       0
total_experience_years         0
field_experience_years         0
dtype: int64

In [12]:
df[df['annual_salary'].isnull()]

,timestamp,age,industry,job_title,job_title_context,annual_salary,additional_compensation,currency,other_currency,income_context,country,state,city,total_experience_years,field_experience_years,education_level,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,NaN,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,NaN,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,NaN,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,NaN,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,NaN,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20365,4/29/2021 13:58:10,25-34,Engineering or Manufacturing,Product development engineer,NaN,NaN,10000.0,USD,NaN,NaN,Usa,Washington,Redmond,2 - 4 years,2 - 4 years,Master's degree,Woman,White
20366,4/29/2021 13:58:26,55-64,Education (Higher Education),Communication Specialist,NaN,NaN,0.0,USD,NaN,NaN,US,Michigan,Ann Arbor,31 - 40 years,11 - 20 years,College degree,Woman,White
20367,4/29/2021 13:58:59,25-34,Computing or Tech,Software Engineer 2,"Basically, one step below Senior level",NaN,12800.0,USD,NaN,NaN,USA,Washington,Seattle,2 - 4 years,2 - 4 years,College degree,Non-binary,White
20368,4/29/2021 13:58:59,25-34,"Marketing, Advertising & PR",Senior Digital Consultant,Communications consultant specializing in digital,NaN,0.0,GBP,NaN,NaN,United Kingdom,NaN,London,5-7 years,5-7 years,College degree,Woman,White
20369,4/29/2021 13:59:22,25-34,Political Campaigns,Campaign Manager,NaN,NaN,12000.0,USD,NaN,"The bonus is if I win a campaign, and represen...",United States,District of Columbia,DC,5-7 years,5-7 years,College degree,Man,White

In [13]:
df['annual_salary'].head()
df['annual_salary'].dtype

dtype('float64')

In [14]:
df['annual_salary'].isna().sum()

np.int64(20302)

In [15]:
df[
    (df['annual_salary'].isna()) &
    (df['gender'] == 'Woman')
]

,timestamp,age,industry,job_title,job_title_context,annual_salary,additional_compensation,currency,other_currency,income_context,country,state,city,total_experience_years,field_experience_years,education_level,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,NaN,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,NaN,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,NaN,3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,NaN,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
6,4/27/2021 11:02:51,25-34,Publishing,Publishing Assistant,NaN,NaN,2000.0,USD,NaN,NaN,USA,South Carolina,Columbia,2 - 4 years,2 - 4 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20363,4/29/2021 13:56:59,25-34,Nonprofits,Data and Quality Assurance Manager,Also act as the Salesforce Administrator,NaN,0.0,USD,NaN,NaN,USA,Illinois,Chicago,2 - 4 years,2 - 4 years,College degree,Woman,White
20364,4/29/2021 13:57:34,18-24,Property or Construction,Executive Assistant,NaN,NaN,0.0,USD,NaN,NaN,United States,Arizona,Scottsdale,5-7 years,5-7 years,High School,Woman,White
20365,4/29/2021 13:58:10,25-34,Engineering or Manufacturing,Product development engineer,NaN,NaN,10000.0,USD,NaN,NaN,Usa,Washington,Redmond,2 - 4 years,2 - 4 years,Master's degree,Woman,White
20366,4/29/2021 13:58:26,55-64,Education (Higher Education),Communication Specialist,NaN,NaN,0.0,USD,NaN,NaN,US,Michigan,Ann Arbor,31 - 40 years,11 - 20 years,College degree,Woman,White
20368,4/29/2021 13:58:59,25-34,"Marketing, Advertising & PR",Senior Digital Consultant,Communications consultant specializing in digital,NaN,0.0,GBP,NaN,NaN,United Kingdom,NaN,London,5-7 years,5-7 years,College degree,Woman,White

In [16]:
cols = [
    'gender',
    'race',
    'country',
    'currency',
    'education_level'
]

for col in cols:
    print("\n", col)
    print(df[col].value_counts(dropna=False).head(20))

 gender
gender
Woman                            21427
Man                               5563
Non-binary                         747
Other or prefer not to answer      299
NaN                                186
Prefer not to answer                 1
Name: count, dtype: int64

 race
race
White                                                                              23274
Asian or Asian American                                                             1431
Black or African American                                                            707
Another option not listed here or prefer not to answer                               632
Hispanic, Latino, or Spanish origin                                                  613
Hispanic, Latino, or Spanish origin, White                                           385
Asian or Asian American, White                                                       344
NaN                                                                                  197
Black or African American, White                                                     123
Middle Eastern or Northern African, White                                             83
Middle Eastern or Northern African                                                    74
Native American or Alaska Native, White                                               68
White, Another option not listed here or prefer not to answer                         65
Native American or Alaska Native                                                      43
Black or African American, Hispanic, Latino, or Spanish origin                        28
Asian or Asian American, Hispanic, Latino, or Spanish origin, White                   15
Asian or Asian American, Hispanic, Latino, or Spanish origin                          14
Black or African American, Hispanic, Latino, or Spanish origin, White                 11
Asian or Asian American, Another option not listed here or prefer not to answer       11
Hispanic, Latino, or Spanish origin, Native American or Alaska Native                 11
Name: count, dtype: int64

 country
country
United States               9036
USA                         7963
US                          2620
Canada                      1576
United States                669
U.S.                         586
UK                           576
United Kingdom               551
USA                          468
Usa                          448
United States of America     431
Australia                    319
United states                209
usa                          187
Germany                      174
England                      134
united states                116
Us                           106
Ireland                      103
New Zealand                   95
Name: count, dtype: int64

 currency
currency
USD        23496
CAD         1677
GBP         1598
EUR          654
AUD/NZD      505
Other        175
CHF           37
SEK           37
JPY           23
ZAR           17
HKD            4
Name: count, dtype: int64

 education_level
education_level
College degree                        13570
Master's degree                        8899
Some college                           2097
PhD                                    1428
Professional degree (MD, JD, etc.)     1329
High School                             659
NaN                                     241
Name: count, dtype: int64

In [19]:
df['country'] = df['country'].replace({
    'USA': 'US',
    'United States': 'US',
    'United States of America': 'US',
    'U.S.': 'US',
    "U.S": 'US',
    'Usa': 'US',
    'usa': 'US',
    'United states': 'US',
    'Us': 'US',
    'UK': 'United Kingdom',
    'U.K.': 'United Kingdom',
    'England': 'United Kingdom',
})

df['country'].value_counts()

country
US                21608
Canada             1576
United Kingdom     1264
United States       669
USA                 468
                  ...
Thailand              1
Liberia               1
1                     1
Nigeria + UK          1
Zambia                1
Name: count, Length: 378, dtype: int64

<StringArray>
[             'US',  'United Kingdom',          'Canada', 'United Kingdom ',
       'Scotland ',  'United States ', 'The Netherlands',      'Australia ',
           'Spain',              'us',
 ...
 'Česká republika',          'Italia',   'Hong KongKong',           'Egypt',
       'Thailand ',         'Liberia',               '1',    'Nigeria + UK',
          'Zambia',               nan]
Length: 379, dtype: str