In [1]:
import numpy as np
import pandas as pd

np.set_printoptions(suppress=True)

In [2]:
# Dataset
data = {
    'Area': [1000, 1500, 2000, 2500, 3000],
    'Bedrooms': [2, 3, 3, 4, 4],
    'Age': [10, 5, 20, 15, 8],
    'Distance': [5, 3, 10, 2, 7],
    'Price': [200000, 300000, 250000, 400000, 500000]
}

df = pd.DataFrame(data)
df

   Area  Bedrooms  Age  Distance   Price
0  1000         2   10         5  200000
1  1500         3    5         3  300000
2  2000         3   20        10  250000
3  2500         4   15         2  400000
4  3000         4    8         7  500000

# 1. Vectors

Each house = one vector (row in dataset)

In [3]:
x1 = df.iloc[0][['Area','Bedrooms','Age','Distance']].to_numpy()
x2 = df.iloc[1][['Area','Bedrooms','Age','Distance']].to_numpy()

x1, x2

(array([1000,    2,   10,    5]), array([1500,    3,    5,    3]))

## Dot Product (Similarity between houses)

In [6]:
np.dot(x1, x2)

np.int64(1500071)

# 2. Matrix Representation

Dataset = Matrix X

In [7]:
X = df[['Area','Bedrooms','Age','Distance']].to_numpy()
y = df['Price'].to_numpy()

X, y

(array([[1000,    2,   10,    5],
        [1500,    3,    5,    3],
        [2000,    3,   20,   10],
        [2500,    4,   15,    2],
        [3000,    4,    8,    7]]),
 array([200000, 300000, 250000, 400000, 500000]))

# 3. Matrix Multiplication (Core ML idea)

Prediction = X · weights

In [8]:
w = np.array([100, 50000, -2000, -10000])  # fake weights

predictions = X @ w
predictions

array([130000, 260000, 210000, 400000, 414000])

# 4. Error (Difference between real and predicted)

In [9]:
error = y - predictions
error

array([70000, 40000, 40000,     0, 86000])

# 5. Transpose

Used in regression formulas

In [10]:
X.T

array([[1000, 1500, 2000, 2500, 3000],
       [   2,    3,    3,    4,    4],
       [  10,    5,   20,   15,    8],
       [   5,    3,   10,    2,    7]])

# 6. Norm (Error size)

In [11]:
np.linalg.norm(error)

np.float64(124482.93055676349)

# 7. Least Squares (Mini ML Model)

Find best weights using linear algebra

In [12]:
w_best = np.linalg.inv(X.T @ X) @ X.T @ y
w_best

array([   75.69170765, 76926.11471192, -6857.83962479,  1965.1988405 ])

# 8. Final Prediction

In [13]:
final_pred = X @ w_best
final_pred

array([170791.53502915, 315922.30400938, 264656.95534638, 397996.53128359,
       493673.25668501])

# 9. Compare Real vs Predicted

In [14]:
pd.DataFrame({
    'Actual': y,
    'Predicted': final_pred
})

   Actual      Predicted
0  200000  170791.535029
1  300000  315922.304009
2  250000  264656.955346
3  400000  397996.531284
4  500000  493673.256685

# Key Takeaways

- Dataset = Matrix
- Each row = Vector
- Prediction = Matrix multiplication
- Learning = solving linear algebra equation
- Linear regression = pure linear algebra